ServiceMax-Engineering/ui-components-lightning

- lib/components/Badge/Badge.js
- lib/components/Badge/Badge.test.js
* added default props & comments for propTypes
* moved things around.
* minor change to tests.
> UI-407 Updates to Badge to match coding standards.

- lib/components/Button/Button.js
- lib/components/Button/Button.test.js
- lib/components/Button/index.js
- stories/ButtonStories.js
PR comments 
- Josh I have left the button type icon-bare, icon- etc as is. It affects the styles. We need to talk before I proceed.If i just have button types without Icon the styles are affected and i need to know how we should handle this.
> Ui 427 button

- lib/components/Container/Container.js
- lib/components/Container/Container.test.js
- Refactor the code structure to established coding standards
- Add default values for props
- Add `validSizes` and `validAligns` props
- Add unit test
> UI-496 Container - Lightning Component

- lib/index.js
- stories/ContainerStories.js
- stories/index.js
- Add stories to Container component
- Add `size` and `alignment` submenu for the documentaion
> UI-613 Storybook for Container

- lib/components/Container/Container.js
- stories/ContainerStories.js
https://servicemax.atlassian.net/browse/UI-611?streamsSourceProduct=jira
Add exact width of Container to the props description and storybook
> UI-611 add exact width of Container to the props description and storybook

- lib/components/Grid/Grid.js
- lib/components/Grid/Grid.test.js
- lib/components/Grid/GridItem.js
- lib/components/Grid/GridItem.test.js
- lib/components/Grid/GridRow.js
- lib/components/Grid/GridRow.test.js
- lib/components/Grid/index.js
- lib/components/utils/util.js
- lib/index.js
- stories/GridStories.js
* Renamed components:
* `Grid` => `Grid`
* `Row` => `GridRow`
* `Col` => `GridItem`
* Updated to match coding standards
* Broke out into multiple files
* Added tests & `propType` comments
> UI-430 Grid component refactor

- lib/components/Radio/Radio.js
- lib/components/Radio/Radio.test.js
- lib/components/Radio/RadioGroup.js
- lib/components/Radio/RadioGroup.test.js
- package-lock.json
- package.json
- stories/RadioStories.js
- Updating to match our coding standards
- Split Radio and RadioGroup components
- Adding basic tests and proptype comments
> Radio and RadioGroup Components refactoring

- lib/components/Popover/Popover.js
- lib/components/Popover/Popover.scss
- lib/components/Popover/Popover.test.js
- lib/components/Popover/PopoverBody.js
- lib/components/Popover/PopoverBody.test.js
- lib/components/Popover/PopoverHeader.js
- lib/components/Popover/PopoverHeader.test.js
- lib/components/Popover/index.js
- lib/components/utils/index.js
- lib/components/utils/util.js
- lib/index.js
- lib/package.scss
- stories/PopoverStories.js
This PR is ~~not~~ ready for reviewing ~~yet~~. I'll let team know when it's ready to be review.
> UI-508 Popover component

- lib/components/Modal/ModalHeader.js
- stories/ModalStories.js
Also remove form elements for Modal storybook because FormElement is in progress
> Fix modal header based on icon export method change

- lib/components/Button/Button.js
- lib/components/Button/Button.test.js
- lib/components/Datepicker/DateInput.js
- lib/components/Input/Input.js
- lib/components/Lookup/Lookup.js
- lib/components/Notification/Notification.js
- lib/components/Picklist/Picklist.js
- lib/components/Pill/Pill.js
- lib/components/SalesPath/SalesPath.js
- lib/components/Table/Table.js
- Change imports to include within curly braces since Icon component was refactored to add another Class. 
https://servicemax.atlassian.net/browse/UI-827
> Import Icon with curly braces

- lib/components/Tree/Tree.js
- lib/components/Tree/Tree.scss
- lib/components/Tree/Tree.test.js
- lib/components/Tree/TreeItem.js
- lib/components/Tree/TreeItem.test.js
- lib/components/Tree/TreeNode.js
- lib/components/Tree/TreeNode.test.js
- lib/components/Tree/index.js
- stories/TreeStories.js
- Refactoring Tree component to match our coding standards.
- Added proptypes.comments and defaultProps.
- Split TreeItem as separate component.
- Added basic unit tests(will re-visit this part).
> UI-517, UI-518  Tree, TreeNode - Lightning Component

- package.json
updating version numbering to be our own. 0.1.11 (since we have about 11 builds / components so far)
> UI-847 preparing lightning repo for deployment to private repo.

- lib/components/Checkbox/CheckboxGroup.js
- lib/components/Form/Form.js
- lib/components/Form/FormElement.js
- lib/components/Form/FormElement.test.js
- lib/components/Input/InputField.js
- lib/components/Label/Label.js
- lib/components/Radio/RadioGroup.js
- lib/components/Toggle/Toggle.js
- lib/components/Toggle/Toggle.test.js
- stories/FormStories.js
- stories/ToggleStories.js
- Refactor + unit test for Form, FormElement and Toggle
- Rewrite storybooks for Form
- Fix Input bug by adding `inputRef` to its `ref`
- Remove `label` props from Checkbox, Radio.
Breaking change of the form pattern:
Before:
```
<Form>
<Input label="Email" />
</Form>
```
Now:
```
<Form>
<FormElement>
<Label>Email</Label>
<Input />
</FormElement>
</Form>
```
> UI-500 UI-501 UI-516: Form, FormElement, Toggle

- lib/components/Button/ButtonGroup.js
- stories/ButtonGroupStories.js
> UI-493-Button Group

- lib/components/Label/Label.js
- lib/components/Label/Label.scss
Bug in Label due to change in component isRequired being added
> Bug in Label

- lib/components/Select/Option.js
- lib/components/Select/Select.js
- lib/components/Select/index.js
- stories/SelectStories.js
*Refactor Select Component
* Update StoryBook
> Ui 705 select

- .eslintrc
- lib/components/Table/Table.js
- lib/components/Table/Table.scss
- lib/components/Table/Table.test.js
- lib/components/Table/TableBody.js
- lib/components/Table/TableBody.test.js
- lib/components/Table/TableHeader.js
- lib/components/Table/TableHeader.test.js
- lib/components/Table/TableHeaderColumn.js
- lib/components/Table/TableHeaderColumn.test.js
- lib/components/Table/TableRow.js
- lib/components/Table/TableRow.test.js
- lib/components/Table/TableRowColumn.js
- lib/components/Table/TableRowColumn.test.js
- lib/components/Table/TableRowColumnActions.js
- lib/components/Table/TableRowColumnActions.test.js
- lib/components/Table/index.js
- stories/TableStories.js
- Refactored code, added defaultProps and propTypes - Table Component.
- Split Table into modular sub-components => TableHeader, TableBody, TableHeaderColumn, TableRow, TableRowColumn, TableRowColumnActions.
- Added basic unit tests.
> UI-513 Table - Lightning Component

- lib/components/Form/FieldSet.js
- lib/components/Form/FieldSet.test.js
- lib/components/Form/Row.js
- lib/components/Form/Row.test.js
- FieldSet component and tests
- Row component and tests
- Move Row out to another file from FieldSet
> UI-499 FieldSet, Row

- package-lock.json
- package.json
minor changes to be able to publish to private npm repo.
@sheela-svmx @mallik-svmx @kokasvmx @hanzge 
needed: 2 approvals.
> UI-727 minor update to package.json to publish

- lib/components/Form/FieldSet.js
- lib/components/Form/FieldSetRow.js
- lib/components/Form/FieldSetRow.test.js
- lib/components/Form/index.js
- lib/index.js
- stories/FormStories.js
Base on our discussion, change all `Row` to `FieldSetRow` so that can match our standard
> Change Row to FieldSetRow

- LICENSE
- lib/components/Button/Button.js
- lib/components/Grid/Grid.js
- lib/components/Grid/GridRow.js
- lib/components/Lookup/Lookup.js
- lib/components/PageHeader/PageHeader.js
- lib/components/Pill/index.js
- lib/components/Spinner/index.js
- lib/components/Tooltip/Tooltip.js
- lib/components/utils/index.js
- lib/components/utils/util.js
- lib/index.js
- lib/package.scss
- package-lock.json
- package.json
* too many changes to list, but including a change to the package.scss.
> UI-994 changes needed to get CRA & lightning to play well together.
